
PYTHON=python

HEALTH_DATA_DIR=$(HOME)/HealthData
FIT_FILE_DIR=$(HEALTH_DATA_DIR)/FitFiles
FITBIT_FILE_DIR=$(HEALTH_DATA_DIR)/FitBitFiles
MSHEALTH_FILE_DIR=$(HEALTH_DATA_DIR)/MSHealth
DB_DIR=$(HEALTH_DATA_DIR)/DBs
BACKUP_DIR=$(HEALTH_DATA_DIR)/Backups
MONITORING_FIT_FILES_DIR=$(FIT_FILE_DIR)/$(YEAR)_Monitoring
SLEEP_FILES_DIR=$(HEALTH_DATA_DIR)/Sleep
ACTIVITES_FIT_FILES_DIR=$(FIT_FILE_DIR)/Activities
WEIGHT_FILES_DIR=$(HEALTH_DATA_DIR)/Weight
RHR_FILES_DIR=$(HEALTH_DATA_DIR)/RHR


TMPDIR = $(shell mktemp -d)

TEST_FILE_DIR=$(HOME)/Downloads
TEST_DB_DIR=$(TMPDIR)
